apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        ports:
        - containerPort: 8080
        env:
        - name: OLLAMA_BASE_URL
          value: "http://ollama:11434"
        - name: WEBUI_SECRET_KEY
          value: ""
        startupProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 30
          periodSeconds: 10
          failureThreshold: 12
        volumeMounts:
        - name: open-webui-volume
          mountPath: /app/backend/data
      volumes:
      - name: open-webui-volume
        persistentVolumeClaim:
          claimName: open-webui-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui
spec:
  selector:
    app: open-webui
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: open-webui-pv
  labels:
    type: local
    app: open-webui
spec:
  storageClassName: "" # Ensure default storage class is used
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/data/open-webui
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-pvc
spec:
  storageClassName: "" # Ensure default storage class is used
  selector:
    matchLabels:
      type: local
      app: open-webui
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi