// Jenkinsfile (Declarative Pipeline)
/* Requires the Docker Pipeline plugin */
// pipeline {
//     agent { docker { image 'maven:3.9.6-eclipse-temurin-17-alpine' } }
//     stages {
//         stage('build') {
//             steps {
//                 sh 'mvn --version'
//             }
//         }
//     }
// }

pipeline {
    agent {
        label 'ubuntu-docker-maven'
    }
    stages {
        stage('Build') {
            steps {
                script {
                    docker.image('maven:3.9.6-eclipse-temurin-17-alpine').inside {
                        sh 'mvn --version'
                    }
                }
            }
        }
    }
}
