# docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: ./monorepo-root/frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8080/api

  backend:
    build:
      context: ./monorepo-root/backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
